@startuml Class diagram
skinparam backgroundColor #FAF9F9
skinparam DefaultFontName Roboto
skinparam style strictuml
hide empty members

set namespaceSeparator ::

class App::Controller {}
class App::Module {}
class App::Service {}

class User::Controller {}
class User::Module {}
class User::Service {}

' Module bundling
App::Module --> User::Module
@enduml
