blank_issues_enabled: false
contact_links:
  - name: Musco Community Support
    url: https://community.musco.nl/
    about: Please ask and answer questions here.
  - name: Musco Security Bugs
    url: https://bugs.musco.nl/
    about: Please report security vulnerabilities here.