@startuml Architecture diagram
!include <archimate/Archimate>

skinparam backgroundColor #FAF9F9
skinparam DefaultFontName Roboto
skinparam style strictuml

Business_Actor(actor, "Musician")

Grouping(http, "HTTP server") {
	Technology_Device(webapp, "Web application")
	Technology_Device(api, "API")
}

Group(dbserver,
	"PostgreSQL server") {
		Technology_Device(db, "PostgreSQL DB")
	}

	Application_Service(firebase, "Firebase")

	Rel_Access_Down(actor, webapp, "HTTP/2.0")
	Rel_Serving_Right(webapp, api, "HTTP/2.0")
	Rel_Serving_Right(api, dbserver, "ODBC")
	Rel_Aggregation_Up(firebase, webapp)
	Rel_Aggregation_Up(firebase, api)
	@enduml
