@startuml Domain model
skinparam style strictuml
skinparam DefaultFontName Roboto
skinparam backgroundColor #FAF9F9

hide empty members

class User {
	name
	email
}

class Absence {
	ochestra
	reasoning
	start
	end
}
class Instrument {
	name
	section
}
class Notice {
	title
	description

}

class Attachment {
	title
	location
	type
}
class Role {}
class Musician {}
class Admin {}
class Moderator {}

class Event {
	name
	description
	date
	startTime
	endTime
}

class Orchestra {
	name
}

class "Role enrollment" {
	from
	until
}

class Attendance {
	remark
}

Role <|-- Musician
Role <|-- Moderator
Role <|-- Admin

Role "1..*" -- "1..*" User
(Role, User) .. "Role enrollment"

User "1" *-- "-user 0..*" Absence: Reports >
User "0..*" -- "0..*" Instrument: Plays >
User "-attendees 0..*" -- "0..*" Event: attends to >
User "-invitees 1..*" -- "0..*" Event: invited for <
(User, Event) .. Attendance

Notice "0..*" --* "-attachments 1" Attachment: contains >
Notice "0..*" -- "-recipients 0..*" User: recieves >
@enduml
