@startuml domain model
skinparam style strictuml
skinparam DefaultFontName Roboto
skinparam backgroundColor #FAF9F9
skinparam ranksep 75
skinparam nodesep 75

hide empty members

class User {
name
email
orchestras
instruments
}

class Absence {
user
ochestra
reasoning
start
end
}
class Instrument {
name
section
}
class Notice {
title
description
recipients
attachments
}

class Attachment {
title
location
type
}
class Role
class Musician
class Admin
class Moderator

class Event {
name
description
invitees
attendees
date
startTime
endTime
}

class Orchestra {
name
}

class Attendance {
remark
}

Role <|-- Musician
Role <|-- Moderator
Role <|-- Admin

User "1..*" -u- "1..*" Role: enrolls as <
User "1" *-u- "0..*" Absence: reports >
User "0..*" -u- "0..*" Notice: receives <
User "0..*" -d- "0..*" Instrument: Plays >
User "1..*" -l- "0..*" Event: invited for <
User "0..*" -l- "1" Attendance: attends to >
User "0..*" -r- "0..*" Orchestra: plays in >

Notice "0..*" -u-* "1" Attachment: contains >

Instrument "0..*" -r- "0..*" Orchestra: contains <

Attendance "1" -- "0..*" Event
@enduml
