@startuml Use case diagram
skinparam backgroundColor #FAF9F9
skinparam DefaultFontName Roboto

left to right direction
:Muzikant:
:Moderator:
:Beheerder:

(Indienen afmelding) AS reportAbsence
(Aanmelden evenement) AS signUpEvent
(Plannen evenement) AS planEvent
(Afhandelen mededeling) AS dispatchNotice
(Uitvoeren startup) AS startUp
(Toewijzen moderator) AS assignMod

Muzikant -- reportAbsence
Muzikant -- signUpEvent
Moderator -- planEvent
Moderator -- dispatchNotice
Beheerder -- startUp
Beheerder -- assignMod
@enduml
